name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  coding-standards:
    name: CS, Rector, PHPStan, Lint, PSALM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        run: make up
      - name: Validate composer
        run: make validate-composer
      - name: Run CS check
        run: make cs-check
      - name: Run rector
        run: make rector
      - name: Run PHPStan
        run: make phpstan
      - name: Run PHP Parallel Lint
        run: make lint
      - name: Run PSALM
        run: make psalm
